server:
  port: 9001

spring:
  application:
    name: employee-service
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/management_system
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    diver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://${DB_URL}:3306/management_system
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: management_system
            client-secret: ${KEYCLOAK_SECRET}
            authorization-grant-type: client_credentials
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}

keycloak:
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT}
  username: ${KEYCLOAK_USER}
  password: ${KEYCLOAK_PASSWORD}
  grant-type: client_credentials
  secret: ${KEYCLOAK_SECRET}
  auth-server-url: ${KEYCLOAK_URL}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL}:8761/eureka/

error:
  messages:
    null-or-empty: "Field cannot be null or empty"
    entity-null: "Entity cannot be null"
    field-value-set-prematurely: "Field value set prematurely"
    field-value-invalid: "Field value invalid"
    value-already-exists: "Field value already exists"

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html